-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS syncs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    device_id BIGINT NOT NULL UNIQUE,
    firmware_version SMALLINT NOT NULL,
    firmware_version_upd SMALLINT,
    firmware_updated_at TIMESTAMPTZ,
    firmware_update_status VARCHAR(32) NOT NULL DEFAULT 'idle',
    cfg_version SMALLINT NOT NULL,
    last_mod_time BIGINT NOT NULL,
    cfg_hash BIGINT NOT NULL,

    CONSTRAINT fk_syncs_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_syncs_device_id ON syncs(device_id);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_syncs()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_syncs_trigger
    BEFORE UPDATE ON syncs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_syncs();

CREATE FUNCTION syncs_set_default_firmware_upd()
    RETURNS trigger AS
$$
BEGIN
    IF NEW.firmware_version_upd IS NULL THEN
        NEW.firmware_version_upd := NEW.firmware_version;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_syncs_default_upd
    BEFORE INSERT ON syncs
    FOR EACH ROW
    EXECUTE FUNCTION syncs_set_default_firmware_upd();

CREATE OR REPLACE FUNCTION update_firmware_date()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.firmware_version > OLD.firmware_version THEN
        NEW.firmware_updated_at := NOW();
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_firmware_date
BEFORE UPDATE ON syncs
FOR EACH ROW
EXECUTE FUNCTION update_firmware_date();
-- +Triggers

-- +Comments
COMMENT ON TABLE syncs IS 'Firmware and configuration sync state for devices';
COMMENT ON COLUMN syncs.id IS 'Primary key of the sync record';
COMMENT ON COLUMN syncs.created_at IS 'Timestamp when the sync record was created';
COMMENT ON COLUMN syncs.updated_at IS 'Timestamp when the sync record was last updated';
COMMENT ON COLUMN syncs.device_id IS 'Foreign key to the related device';
COMMENT ON COLUMN syncs.firmware_version IS 'Current version of the device firmware';
COMMENT ON COLUMN syncs.firmware_version_upd IS 'Target firmware version for update';
COMMENT ON COLUMN syncs.firmware_updated_at IS 'Timestamp of the last firmware update';
COMMENT ON COLUMN syncs.cfg_version IS 'Version of the applied configuration';
COMMENT ON COLUMN syncs.last_mod_time IS 'Last modification time in seconds';
COMMENT ON COLUMN syncs.cfg_hash IS 'Hash of the last applied configuration';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_syncs_trigger ON syncs;
DROP TRIGGER IF EXISTS trg_syncs_default_upd ON syncs;
DROP TRIGGER IF EXISTS trg_update_firmware_date ON syncs;

DROP FUNCTION IF EXISTS syncs_set_default_firmware_upd();
DROP FUNCTION IF EXISTS set_updated_at_syncs();
DROP FUNCTION IF EXISTS update_firmware_date();

DROP TABLE IF EXISTS syncs;
-- +goose StatementEnd
