-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS group_user_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,

    CONSTRAINT fk_group_user_devices_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_user_devices_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,

    CONSTRAINT unique_user_group_device UNIQUE (group_id, device_id)
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_group_user_devices_group_id ON group_user_devices(group_id);
CREATE INDEX IF NOT EXISTS idx_group_user_devices_device_id ON group_user_devices(device_id);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION fn_remove_device_from_user_groups()
RETURNS TRIGGER AS $$
BEGIN
    IF OLD.user_uuid IS NOT NULL AND NEW.user_uuid IS NULL THEN
        DELETE FROM group_user_devices
        USING groups
        WHERE group_user_devices.group_id = groups.id
            AND groups.user_uuid = OLD.user_uuid
            AND group_user_devices.device_id = OLD.id;
    END IF;

    IF OLD.owner_uuid IS NOT NULL AND NEW.owner_uuid IS NULL THEN
        DELETE FROM group_user_devices
        USING groups
        WHERE group_user_devices.group_id = groups.id
            AND groups.user_uuid = OLD.owner_uuid
            AND group_user_devices.device_id = OLD.id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_remove_device_from_groups
AFTER UPDATE OF user_uuid, owner_uuid ON devices
FOR EACH ROW
EXECUTE FUNCTION fn_remove_device_from_user_groups();
-- +Triggers

-- +Comments
COMMENT ON TABLE group_user_devices IS 'Many-to-many link between groups and devices';
COMMENT ON COLUMN group_user_devices.id IS 'Primary unique identifier';
COMMENT ON COLUMN group_user_devices.group_id IS 'Foreign key to the group';
COMMENT ON COLUMN group_user_devices.device_id IS 'Foreign key to the device';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trg_remove_device_from_groups ON devices;
DROP FUNCTION IF EXISTS fn_remove_device_from_user_groups();

DROP TABLE IF EXISTS group_user_devices;
-- +goose StatementEnd
