-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS device_confs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    device_id BIGINT NOT NULL UNIQUE,
    password VARCHAR(255),
    request_configuration_on_connect BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_device_confs_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_device_confs_device_id ON device_confs(device_id);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_device_confs()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_device_confs_trigger
    BEFORE UPDATE ON device_confs
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_device_confs();
-- +Triggers

-- +Comments
COMMENT ON TABLE device_confs IS 'Connection settings and credentials for devices';
COMMENT ON COLUMN device_confs.id IS 'Primary key of the device configuration';
COMMENT ON COLUMN device_confs.created_at IS 'Timestamp when the configuration was created';
COMMENT ON COLUMN device_confs.updated_at IS 'Timestamp when the configuration was last updated';
COMMENT ON COLUMN device_confs.device_id IS 'Foreign key to the related device (one-to-one)';
COMMENT ON COLUMN device_confs.password IS 'Password required for device access';
COMMENT ON COLUMN device_confs.request_configuration_on_connect IS 'If true, request configuration upon connection';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_device_confs_trigger ON device_confs;
DROP FUNCTION IF EXISTS set_updated_at_device_confs();

DROP TABLE IF EXISTS device_confs;
-- +goose StatementEnd
