-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    role_code VARCHAR(50) NOT NULL,

    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_code) REFERENCES roles(code) ON DELETE RESTRICT
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_user_roles_user_uuid ON user_roles(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_roles()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_roles_trigger
    BEFORE UPDATE ON user_roles
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_roles();
-- +Triggers

-- +Comments
COMMENT ON TABLE user_roles IS 'Table linking users to specific roles in the system';
COMMENT ON COLUMN user_roles.id IS 'Primary unique identifier';
COMMENT ON COLUMN user_roles.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN user_roles.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN user_roles.user_uuid IS 'Uuid of the user (unique)';
COMMENT ON COLUMN user_roles.role_code IS 'Foreign key to roles table';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_roles_trigger ON user_roles;
DROP FUNCTION IF EXISTS set_updated_at_user_roles();

DROP TABLE IF EXISTS user_roles;
-- +goose StatementEnd
