-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS analytic_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL,

    device_id BIGINT NOT NULL,
    cfg_hash BIGINT NOT NULL,
    rmq_published BOOLEAN NOT NULL DEFAULT false,
    device_online BOOLEAN NOT NULL DEFAULT false,
    error_reason VARCHAR(255) NULL DEFAULT NULL,

    CONSTRAINT fk_analytic_records_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_analytic_records_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_analytic_records_created_at ON analytic_records(created_at);
CREATE INDEX IF NOT EXISTS idx_analytic_records_user_uuid ON analytic_records(user_uuid);
CREATE INDEX IF NOT EXISTS idx_analytic_records_device_id ON analytic_records(device_id);
CREATE INDEX IF NOT EXISTS idx_analytic_records_cfg_hash ON analytic_records(cfg_hash);
-- +Indexes

-- +Comments
COMMENT ON TABLE analytic_records IS 'Analytics events for configuration changes and device state';
COMMENT ON COLUMN analytic_records.id IS 'Primary unique identifier';
COMMENT ON COLUMN analytic_records.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN analytic_records.user_uuid IS 'Uuid of the user who triggered the event';
COMMENT ON COLUMN analytic_records.device_id IS 'Foreign key to the related device';
COMMENT ON COLUMN analytic_records.cfg_hash IS 'Hash of the configuration involved in the event';
COMMENT ON COLUMN analytic_records.rmq_published IS 'Whether the event was published to RabbitMQ';
COMMENT ON COLUMN analytic_records.device_online IS 'Whether the device was online at event time';
COMMENT ON COLUMN analytic_records.error_reason IS 'Error description if the event failed';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS analytic_records;
-- +goose StatementEnd
