-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS product_analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NULL,
    role_code VARCHAR(64) NULL,
    session_id VARCHAR(64) NOT NULL,
    event_name VARCHAR(96) NOT NULL,
    category VARCHAR(48) NOT NULL,
    source VARCHAR(24) NOT NULL DEFAULT 'web',
    path VARCHAR(512) NULL,
    entity_type VARCHAR(48) NULL,
    entity_id VARCHAR(128) NULL,
    device_id BIGINT NULL,
    success BOOLEAN NULL,
    duration_ms INTEGER NULL,
    error_code VARCHAR(128) NULL,
    app_version VARCHAR(64) NULL,
    properties JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT uq_product_analytics_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_product_analytics_events_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE,
    CONSTRAINT fk_product_analytics_events_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE SET NULL,
    CONSTRAINT chk_product_analytics_events_duration CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_product_analytics_events_occurred_at ON product_analytics_events(occurred_at);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_user_time ON product_analytics_events(user_uuid, occurred_at);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_name_time ON product_analytics_events(event_name, occurred_at);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_session ON product_analytics_events(session_id);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_device_time ON product_analytics_events(device_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_error ON product_analytics_events(error_code, occurred_at) WHERE error_code IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_product_analytics_events_properties ON product_analytics_events USING GIN(properties);

COMMENT ON TABLE product_analytics_events IS 'Privacy-safe product events sent asynchronously by NeoSync clients';
COMMENT ON COLUMN product_analytics_events.properties IS 'Sanitized event dimensions; never contains form values, secrets or request bodies';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS product_analytics_events;
-- +goose StatementEnd
