-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS configuration_templates (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_ut TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
	user_uuid VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	model VARCHAR(50) NULL DEFAULT NULL,
	type_of_saving VARCHAR(50) NOT NULL DEFAULT 'modified_ones' CHECK (type_of_saving IN ('modified_ones', 'full')),
	cfg_data BYTEA NOT NULL,

	CONSTRAINT fk_configuration_templates_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_configuration_templates_user_uuid ON configuration_templates(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_configuration_templates()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_configuration_templates_trigger
    BEFORE UPDATE ON configuration_templates
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_configuration_templates();
-- +Triggers
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_configuration_templates_trigger ON configuration_templates;
DROP FUNCTION IF EXISTS set_updated_at_configuration_templates();

DROP TABLE IF EXISTS configuration_templates;
-- +goose StatementEnd
