export const BITs = {
	DEVICE_FUNCTION_3: {
		MULTI_APN_MODE_BIT_0: 3,
		MULTI_APN_MODE_BIT_1: 4,
	},
	CUSTOM_MASK_DEFAULT_FALSE_1: {
		AUTOMATIC_POWER_VIA_USB: 0,
		FORBIDDING_POWER_POWER_BUTTON: 1,
		SOS_BUTTON: 2,
		SOS_POLARITY: 5,
		RECEIVE_TAG_IDENTIFIER: 6,
		REPLACE_COORDINATES_WITH_BLE_TAGS: 7,
	},
	CUSTOM_MASK_DEFAULT_TRUE_1: {
		SEND_SMS_MESSAGES: 0,
	},
	DEVICE_FUNCTIONS: {
		DEVICE_MODE_TRACKER: 0,
		REMOTE_CONFIG_ALWAYS: 1,
		ROAMING_ENABLED: 2,
		ROAMING_REMEMBER_OPERATORS: 3,
		AIN_EXPECTED_STATE_ONE: 4,
		AIN_NUMBER_ZERO: 5,
		OUTPUT_ON_TAG_LOST_HIGH: 6,
		ROAMING_DELAY_ENABLE: 7,
	},
	DEVICE_FUNCTION_2: {
		COORDINATE_FREEZE_AT_INVALID: 7,
	},
	BEACON_MODE_GNSS_ACTIVE: {
		BEACON_MODE_GNSS_ACTIVE: 2,
		BEACON_MODE_GSM_SLEEP: 0,
	},
	ADM20_MODE: {
		ADM20_PERIODIC_RFID: 0,
		ADM20_GUARANTEED_RFID: 1,
		ADM20_TAG_DETECTION: 3,
	},
} as const;
