-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    access_treker_create BOOLEAN NOT NULL DEFAULT FALSE,
    access_treker_edit BOOLEAN NOT NULL DEFAULT FALSE,
    access_treker_delete BOOLEAN NOT NULL DEFAULT FALSE,
    access_group_manage BOOLEAN NOT NULL DEFAULT FALSE,
    access_configuration_read BOOLEAN NOT NULL DEFAULT FALSE,
    access_configuration_apply BOOLEAN NOT NULL DEFAULT FALSE,
    access_configuration_history BOOLEAN NOT NULL DEFAULT FALSE,
    access_command_send BOOLEAN NOT NULL DEFAULT FALSE,
    access_log_read BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_user_accesses_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_user_accesses_user_uuid ON user_accesses(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_accesses()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_accesses_trigger
    BEFORE UPDATE ON user_accesses
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_accesses();
-- +Triggers

-- +Comments
COMMENT ON TABLE user_accesses IS 'Fine-grained access permissions for users';
COMMENT ON COLUMN user_accesses.id IS 'Primary unique identifier';
COMMENT ON COLUMN user_accesses.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN user_accesses.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN user_accesses.user_uuid IS 'Uuid of the user';
COMMENT ON COLUMN user_accesses.access_treker_create IS 'Permission to create tracker records';
COMMENT ON COLUMN user_accesses.access_treker_edit IS 'Permission to edit tracker records';
COMMENT ON COLUMN user_accesses.access_treker_delete IS 'Permission to delete tracker records';
COMMENT ON COLUMN user_accesses.access_group_manage IS 'Permission to manage device groups';
COMMENT ON COLUMN user_accesses.access_configuration_read IS 'Permission to read device configurations';
COMMENT ON COLUMN user_accesses.access_configuration_apply IS 'Permission to apply device configurations';
COMMENT ON COLUMN user_accesses.access_configuration_history IS 'Permission to view configuration history';
COMMENT ON COLUMN user_accesses.access_command_send IS 'Permission to send commands to devices';
COMMENT ON COLUMN user_accesses.access_log_read IS 'Permission to read system logs';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_accesses_trigger ON user_accesses;
DROP FUNCTION IF EXISTS set_updated_at_user_accesses();

DROP TABLE IF EXISTS user_accesses;
-- +goose StatementEnd
