-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS device_model_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    device_model VARCHAR(50) NOT NULL UNIQUE,
    firmware_url TEXT NOT NULL,
    firmware_cache_key VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADMP50', 'http://www.update.neomatica.ru/admp50/', 'latestETag:ADMP50');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADMP50LTE', 'http://www.update.neomatica.ru/admp50lte/', 'latestETag:ADMP50LTE');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM007', 'http://www.update.neomatica.ru/adm007/', 'latestETag:ADM007');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM007BLE', 'http://www.update.neomatica.ru/adm007ble/', 'latestETag:ADM007BLE');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM333', 'http://www.update.neomatica.ru/adm333/', 'latestETag:ADM333');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM333BLE', 'http://www.update.neomatica.ru/adm333ble/', 'latestETag:ADM333BLE');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM333V2', 'http://www.update.neomatica.ru/adm333v2/', 'latestETag:ADM333V2');
INSERT INTO device_model_sources (device_model, firmware_url, firmware_cache_key) VALUES ('ADM500', 'http://www.update.neomatica.ru/adm500/', 'latestETag:ADM500');

-- +Comments
COMMENT ON TABLE device_model_sources IS 'Firmware update sources for supported device models';
COMMENT ON COLUMN device_model_sources.id IS 'Primary unique identifier';
COMMENT ON COLUMN device_model_sources.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN device_model_sources.device_model IS 'Unique device model code';
COMMENT ON COLUMN device_model_sources.firmware_url IS 'URL to fetch firmware updates for this model';
COMMENT ON COLUMN device_model_sources.firmware_cache_key IS 'Cache key for tracking firmware ETag';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS device_model_sources;
-- +goose StatementEnd
