-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name_key VARCHAR(100) NOT NULL,
    desc_key VARCHAR(100) NOT NULL
);

INSERT INTO roles (code, name_key, desc_key) VALUES ('USER', 'role-user-name', 'role-user-desc');
INSERT INTO roles (code, name_key, desc_key) VALUES ('DEALER_SUPPORT', 'role-dealer-support-name', 'role-dealer-support-desc');
INSERT INTO roles (code, name_key, desc_key) VALUES ('DEALER', 'role-dealer-name', 'role-dealer-desc');
INSERT INTO roles (code, name_key, desc_key) VALUES ('SUPPORT', 'role-support-name', 'role-support-desc');
INSERT INTO roles (code, name_key, desc_key) VALUES ('SUPERADMIN', 'role-superadmin-name', 'role-superadmin-desc');

-- +Comments
COMMENT ON TABLE roles IS 'User roles and access levels in the system';
COMMENT ON COLUMN roles.id IS 'Primary key';
COMMENT ON COLUMN roles.code IS 'Unique role index used for identification';
COMMENT ON COLUMN roles.name_key IS 'Role name';
COMMENT ON COLUMN roles.desc_key IS 'Detailed description of the role capabilities';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS roles;
-- +goose StatementEnd
