-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NULL DEFAULT NULL,
    owner_uuid VARCHAR(255) NULL DEFAULT NULL,

    name VARCHAR(30),
    phone VARCHAR(25),
    name_organization VARCHAR(150),

    imei VARCHAR(15) NOT NULL UNIQUE,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    device_model VARCHAR(50) NULL DEFAULT NULL,
    device_extended_model VARCHAR(50) NULL DEFAULT NULL,
    activated BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_devices_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE SET NULL,
    CONSTRAINT fk_devices_owner FOREIGN KEY (owner_uuid) REFERENCES user_cores(user_uuid) ON DELETE SET NULL
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_devices_imei ON devices(imei);
CREATE INDEX IF NOT EXISTS idx_devices_user_uuid ON devices(user_uuid);
CREATE INDEX IF NOT EXISTS idx_devices_owner_uuid ON devices(owner_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_devices()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_devices_trigger
    BEFORE UPDATE ON devices
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_devices();
-- +Triggers

-- +Comments
COMMENT ON TABLE devices IS 'GPS tracking devices registered in the system';
COMMENT ON COLUMN devices.id IS 'Primary key of the device';
COMMENT ON COLUMN devices.created_at IS 'Timestamp when the device record was created';
COMMENT ON COLUMN devices.updated_at IS 'Timestamp when the device record was last updated';
COMMENT ON COLUMN devices.user_uuid IS 'Uuid of the dealer user the device belongs to';
COMMENT ON COLUMN devices.owner_uuid IS 'Uuid of the end-user who owns the device';
COMMENT ON COLUMN devices.name IS 'Display name of the device';
COMMENT ON COLUMN devices.phone IS 'Phone number associated with the device SIM';
COMMENT ON COLUMN devices.name_organization IS 'Organization name linked to the device';
COMMENT ON COLUMN devices.imei IS 'Unique IMEI number of the device';
COMMENT ON COLUMN devices.status IS 'Device status (true = active, false = inactive)';
COMMENT ON COLUMN devices.device_model IS 'Model of the device';
COMMENT ON COLUMN devices.device_extended_model IS 'Extended or sub-model variant of the device';
COMMENT ON COLUMN devices.activated IS 'Whether the device has been activated';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_devices_trigger ON devices;
DROP FUNCTION IF EXISTS set_updated_at_devices();

DROP TABLE IF EXISTS devices;
-- +goose StatementEnd
