-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_cores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    parent_uuid VARCHAR(255) NULL DEFAULT NULL,
    can_view_child_groups BOOLEAN DEFAULT FALSE,
	force_neosync_configuration_priority BOOLEAN NOT NULL DEFAULT FALSE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL CHECK (char_length(password) > 5),
    refresh_token VARCHAR(255) UNIQUE,

    CONSTRAINT fk_user_cores_parent FOREIGN KEY (parent_uuid) REFERENCES user_cores(user_uuid) ON DELETE SET NULL
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_user_cores_email ON user_cores(email);
CREATE INDEX IF NOT EXISTS idx_user_cores_user_uuid ON user_cores(user_uuid);
CREATE INDEX IF NOT EXISTS idx_user_cores_parent_uuid ON user_cores(parent_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_cores()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_cores_trigger
    BEFORE UPDATE ON user_cores
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_cores();
-- +Triggers

-- +Comments
COMMENT ON COLUMN user_cores.id IS 'Primary unique identifier';
COMMENT ON COLUMN user_cores.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN user_cores.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN user_cores.user_uuid IS 'Uuid of the user';
COMMENT ON COLUMN user_cores.parent_uuid IS 'Uuid of the parent user (nullable)';
COMMENT ON COLUMN user_cores.can_view_child_groups IS 'Whether the user can view groups of child accounts';
COMMENT ON COLUMN user_cores.email IS 'User email address (unique)';
COMMENT ON COLUMN user_cores.password IS 'Hashed user password';
COMMENT ON COLUMN user_cores.refresh_token IS 'JWT refresh token for authentication (unique)';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_cores_trigger ON user_cores;
DROP FUNCTION IF EXISTS set_updated_at_user_cores();

DROP TABLE IF EXISTS user_cores;
-- +goose StatementEnd
