-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    device_id BIGINT NOT NULL UNIQUE,
    cfg_hash BIGINT NOT NULL,
    cfg_pushed_hash BIGINT NOT NULL DEFAULT 0,
    cfg_sync_status VARCHAR(32) NOT NULL DEFAULT 'idle',
    cfg_sync_error VARCHAR(255) NULL DEFAULT NULL,
    cfg_data BYTEA NULL DEFAULT NULL,

    CONSTRAINT fk_configurations_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_configurations_device_id ON configurations(device_id);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_configurations()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_configurations_trigger
    BEFORE UPDATE ON configurations
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_configurations();
-- +Triggers

-- +Comments
COMMENT ON TABLE configurations IS 'Current configuration snapshot for each device';
COMMENT ON COLUMN configurations.id IS 'Primary key of the configuration snapshot';
COMMENT ON COLUMN configurations.created_at IS 'Timestamp when the snapshot was created';
COMMENT ON COLUMN configurations.updated_at IS 'Timestamp when the snapshot was last updated';
COMMENT ON COLUMN configurations.device_id IS 'Foreign key to the related device';
COMMENT ON COLUMN configurations.cfg_hash IS 'Hash representing this configuration version';
COMMENT ON COLUMN configurations.cfg_pushed_hash IS 'Hash of the configuration last actually sent to the device via SET_CFG; 0 means never sent';
COMMENT ON COLUMN configurations.cfg_sync_status IS 'Synchronization status: idle, syncing, synced, error';
COMMENT ON COLUMN configurations.cfg_sync_error IS 'Error message from the last failed sync attempt';
COMMENT ON COLUMN configurations.cfg_data IS 'Configuration data in binary format (can be null)';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_configurations_trigger ON configurations;
DROP FUNCTION IF EXISTS set_updated_at_configurations();

DROP TABLE IF EXISTS configurations;
-- +goose StatementEnd
