-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS configuration_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apply_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    device_id BIGINT NOT NULL,
    cfg_hash BIGINT NOT NULL,
    cfg_data BYTEA NULL DEFAULT NULL,

    CONSTRAINT fk_configuration_history_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_configuration_history_device_id ON configuration_history(device_id);
CREATE INDEX IF NOT EXISTS idx_configuration_history_device_apply_at ON configuration_history(device_id, apply_at DESC);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION trg_configuration_history()
RETURNS TRIGGER AS $$
DECLARE
    oldest_id INT;
    cnt INT;
BEGIN
    IF NEW.cfg_hash IS DISTINCT FROM OLD.cfg_hash OR NEW.cfg_data IS DISTINCT FROM OLD.cfg_data THEN
        -- Считаем, сколько историй уже есть для устройства
        SELECT COUNT(*) INTO cnt
        FROM configuration_history
        WHERE device_id = NEW.device_id;

        IF cnt >= 15 THEN
            -- Находим старейшую запись для этого устройства
            SELECT id INTO oldest_id
            FROM configuration_history
            WHERE device_id = NEW.device_id
            ORDER BY apply_at ASC
            LIMIT 1;

            -- Перезаписываем старую запись
            UPDATE configuration_history
            SET cfg_hash = NEW.cfg_hash,
                cfg_data = NEW.cfg_data,
                apply_at = now()
            WHERE id = oldest_id;
        ELSE
            -- Вставляем новую запись, пока лимит не достигнут
            INSERT INTO configuration_history (apply_at, device_id, cfg_hash, cfg_data)
            VALUES (now(), NEW.device_id, NEW.cfg_hash, NEW.cfg_data);
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_configuration_history
AFTER UPDATE ON configurations
FOR EACH ROW
EXECUTE FUNCTION trg_configuration_history();
-- +Triggers

-- +Comments
COMMENT ON TABLE configuration_history IS 'Rolling history of applied device configurations (max 15 per device)';
COMMENT ON COLUMN configuration_history.id IS 'Primary unique identifier';
COMMENT ON COLUMN configuration_history.apply_at IS 'Timestamp when the configuration was applied';
COMMENT ON COLUMN configuration_history.device_id IS 'Foreign key to the related device';
COMMENT ON COLUMN configuration_history.cfg_hash IS 'Hash of the applied configuration';
COMMENT ON COLUMN configuration_history.cfg_data IS 'Configuration data in binary format';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trigger_configuration_history ON configurations;
DROP FUNCTION IF EXISTS trg_configuration_history();

DROP TABLE IF EXISTS configuration_history;
-- +goose StatementEnd
