-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NULL DEFAULT NULL,
    name VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,

    can_edit_group BOOLEAN NOT NULL DEFAULT true,
    can_manage_devices BOOLEAN NOT NULL DEFAULT true,
    can_read_config BOOLEAN NOT NULL DEFAULT true,
    can_edit_config BOOLEAN NOT NULL DEFAULT true,
    can_send_commands BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT fk_groups_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_groups_user_uuid ON groups(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_groups()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_groups_trigger
    BEFORE UPDATE ON groups
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_groups();
-- +Triggers

-- +Comments
COMMENT ON TABLE groups IS 'Device groups owned or shared by users';
COMMENT ON COLUMN groups.id IS 'Primary key of the group';
COMMENT ON COLUMN groups.created_at IS 'Timestamp when the group record was created';
COMMENT ON COLUMN groups.updated_at IS 'Timestamp when the group record was last updated';
COMMENT ON COLUMN groups.user_uuid IS 'Uuid of the user who owns the group';
COMMENT ON COLUMN groups.name IS 'Name of the group';
COMMENT ON COLUMN groups.description IS 'Description or purpose of the group';
COMMENT ON COLUMN groups.can_edit_group IS 'Whether group members can edit group settings';
COMMENT ON COLUMN groups.can_manage_devices IS 'Whether group members can add or remove devices';
COMMENT ON COLUMN groups.can_read_config IS 'Whether group members can read device configurations';
COMMENT ON COLUMN groups.can_edit_config IS 'Whether group members can edit device configurations';
COMMENT ON COLUMN groups.can_send_commands IS 'Whether group members can send commands to devices';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_groups_trigger ON groups;
DROP FUNCTION IF EXISTS set_updated_at_groups();

DROP TABLE IF EXISTS groups;
-- +goose StatementEnd
