-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS accesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name_key VARCHAR(100) NOT NULL
);

INSERT INTO accesses (code, name_key) VALUES('FULL', 'access-full');
INSERT INTO accesses (code, name_key) VALUES('READ_ONLY', 'access-read-only');
INSERT INTO accesses (code, name_key) VALUES('NONE', 'access-none');

-- +Comments
COMMENT ON TABLE accesses IS 'Access level definitions for group sharing';
COMMENT ON COLUMN accesses.id IS 'Primary key of the access record';
COMMENT ON COLUMN accesses.code IS 'Unique index representing access type';
COMMENT ON COLUMN accesses.name_key IS 'Name of the access level or permission';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS accesses;
-- +goose StatementEnd
