-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS user_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL UNIQUE,
    name_organization VARCHAR(150),
    locality VARCHAR(150),
    phone VARCHAR(25) NOT NULL DEFAULT '' CHECK (phone = '' OR char_length(phone) > 8),
    language VARCHAR(3) NOT NULL DEFAULT 'ru' CHECK (language IN ('ru', 'en', 'es')),

    CONSTRAINT fk_user_contacts_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_user_contacts_user_uuid ON user_contacts(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_user_contacts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_user_contacts_trigger
    BEFORE UPDATE ON user_contacts
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_user_contacts();
-- +Triggers

-- +Comments
COMMENT ON COLUMN user_contacts.id IS 'Primary unique identifier';
COMMENT ON COLUMN user_contacts.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN user_contacts.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN user_contacts.user_uuid IS 'Uuid of the associated user (must be unique)';
COMMENT ON COLUMN user_contacts.name_organization IS 'Name of the organization or individual contact';
COMMENT ON COLUMN user_contacts.locality IS 'City or locality of the contact';
COMMENT ON COLUMN user_contacts.phone IS 'Phone number of the contact';
COMMENT ON COLUMN user_contacts.language IS 'Language preference: ''ru'', ''en'', or ''es''';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_user_contacts_trigger ON user_contacts;
DROP FUNCTION IF EXISTS set_updated_at_user_contacts();

DROP TABLE IF EXISTS user_contacts;
-- +goose StatementEnd
