-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS device_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    execute_until TIMESTAMPTZ,

    session_id VARCHAR(255) NOT NULL,
    user_uuid VARCHAR(255) NOT NULL,

    send_mode VARCHAR(20) NOT NULL DEFAULT 'instant' CHECK (send_mode IN ('instant', 'on_connect')),
    status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'inprogress', 'executionerror', 'notcompleted', 'completed')),

    command TEXT NOT NULL,

    CONSTRAINT fk_device_commands_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_device_commands_user_uuid ON device_commands(user_uuid);
CREATE INDEX IF NOT EXISTS idx_device_commands_user_created_at ON device_commands(user_uuid, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_device_commands_session_user ON device_commands(session_id, user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_device_commands()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_device_commands_trigger
    BEFORE UPDATE ON device_commands
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_device_commands();
-- +Triggers

-- +Comments
COMMENT ON TABLE device_commands IS 'Commands sent to devices by users';
COMMENT ON COLUMN device_commands.id IS 'Primary unique identifier';
COMMENT ON COLUMN device_commands.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN device_commands.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN device_commands.execute_until IS 'Deadline after which the command expires';
COMMENT ON COLUMN device_commands.session_id IS 'Session identifier for grouping related commands';
COMMENT ON COLUMN device_commands.user_uuid IS 'Uuid of the user who sent the command';
COMMENT ON COLUMN device_commands.send_mode IS 'Delivery mode: instant or on_connect';
COMMENT ON COLUMN device_commands.status IS 'Command status: pending, inprogress, executionerror, notcompleted, completed';
COMMENT ON COLUMN device_commands.command IS 'Command payload text';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_device_commands_trigger ON device_commands;
DROP FUNCTION IF EXISTS set_updated_at_device_commands();

DROP TABLE IF EXISTS device_commands;
-- +goose StatementEnd
