-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS company_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    company_id BIGINT NOT NULL,
    device_id BIGINT NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    error_message TEXT NULL,

    attempts INTEGER NOT NULL DEFAULT 0,

    cfg_data BYTEA NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,
    last_sent_at TIMESTAMPTZ NULL,
    confirmation_deadline TIMESTAMPTZ NULL,
    next_attempt_at TIMESTAMPTZ NULL,

    last_observed_cfg_hash BIGINT NULL,
    last_observed_at TIMESTAMPTZ NULL,

    attempt_token TEXT NULL,
    lease_until TIMESTAMPTZ NULL,

    CONSTRAINT fk_company_tasks_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_company_tasks_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_company_tasks_company_id ON company_tasks(company_id);
CREATE INDEX IF NOT EXISTS idx_company_tasks_device_id ON company_tasks(device_id);
CREATE INDEX IF NOT EXISTS idx_company_tasks_company_status ON company_tasks(company_id, status);
CREATE INDEX IF NOT EXISTS idx_company_tasks_delivery ON company_tasks(expires_at, device_id) WHERE status IN ('pending', 'queued', 'sending', 'awaiting_confirmation');
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_company_tasks()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_company_tasks_trigger
    BEFORE UPDATE ON company_tasks
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_company_tasks();
-- +Triggers

-- +Comments
COMMENT ON TABLE company_tasks IS 'Per-device tasks within a bulk provisioning job';
COMMENT ON COLUMN company_tasks.id IS 'Primary unique identifier';
COMMENT ON COLUMN company_tasks.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN company_tasks.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN company_tasks.company_id IS 'Foreign key to the parent provisioning job';
COMMENT ON COLUMN company_tasks.device_id IS 'Foreign key to the target device';
COMMENT ON COLUMN company_tasks.status IS 'Task status: pending, queued, sending, awaiting_confirmation, completed, failed, expired, cancelled';
COMMENT ON COLUMN company_tasks.error_message IS 'Error description if the task failed';
COMMENT ON COLUMN company_tasks.attempts IS 'Number of execution attempts';
COMMENT ON COLUMN company_tasks.cfg_data IS 'Configuration payload to send to the device';
COMMENT ON COLUMN company_tasks.expires_at IS 'Task expiration timestamp';
COMMENT ON COLUMN company_tasks.last_sent_at IS 'Timestamp of the last configuration send';
COMMENT ON COLUMN company_tasks.confirmation_deadline IS 'Deadline for device configuration confirmation';
COMMENT ON COLUMN company_tasks.next_attempt_at IS 'Timestamp when the next delivery attempt is allowed';
COMMENT ON COLUMN company_tasks.last_observed_cfg_hash IS 'Last configuration hash observed from the device';
COMMENT ON COLUMN company_tasks.last_observed_at IS 'Timestamp when the configuration hash was last observed';
COMMENT ON COLUMN company_tasks.attempt_token IS 'Unique token identifying the current delivery attempt';
COMMENT ON COLUMN company_tasks.lease_until IS 'Timestamp until which the current delivery attempt is leased';-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_company_tasks_trigger ON company_tasks;
DROP FUNCTION IF EXISTS set_updated_at_company_tasks();

DROP TABLE IF EXISTS company_tasks;
-- +goose StatementEnd
