-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS device_command_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),

    command_id BIGINT NOT NULL,
    device_imei VARCHAR(15) NOT NULL,

    status VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'inprogress', 'executionerror', 'notcompleted', 'completed')),
    response TEXT,

    CONSTRAINT fk_device_command_executions_command FOREIGN KEY (command_id) REFERENCES device_commands(id) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_device_command_executions_command_id ON device_command_executions(command_id);
CREATE INDEX IF NOT EXISTS idx_device_command_executions_device_imei ON device_command_executions(device_imei);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_device_command_executions()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_device_command_executions_trigger
    BEFORE UPDATE ON device_command_executions
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_device_command_executions();
-- +Triggers

-- +Comments
COMMENT ON TABLE device_command_executions IS 'Per-device execution results for sent commands';
COMMENT ON COLUMN device_command_executions.id IS 'Primary unique identifier';
COMMENT ON COLUMN device_command_executions.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN device_command_executions.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN device_command_executions.command_id IS 'Foreign key to the parent command';
COMMENT ON COLUMN device_command_executions.device_imei IS 'IMEI of the target device';
COMMENT ON COLUMN device_command_executions.status IS 'Execution status: pending, inprogress, executionerror, notcompleted, completed';
COMMENT ON COLUMN device_command_executions.response IS 'Response text returned by the device';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_device_command_executions_trigger ON device_command_executions;
DROP FUNCTION IF EXISTS set_updated_at_device_command_executions();

DROP TABLE IF EXISTS device_command_executions;
-- +goose StatementEnd
