-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    ttl INTEGER NOT NULL DEFAULT 1,
    existing_task_action VARCHAR(50) NOT NULL DEFAULT 'skip',
    launch_mode VARCHAR(50) NOT NULL DEFAULT 'all',
    incompatible_action VARCHAR(50) NOT NULL DEFAULT 'exclude',
    configuration_source VARCHAR(50) NOT NULL DEFAULT 'template_sources' CHECK (configuration_source IN ('device_sources', 'template_sources', 'file_sources')),
	configuration_source_data BYTEA NOT NULL,
	source_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT fk_companies_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_companies_user_uuid ON companies(user_uuid);
-- +Indexes

-- +Triggers
CREATE OR REPLACE FUNCTION set_updated_at_companies()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at_companies_trigger
    BEFORE UPDATE ON companies
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_companies();
-- +Triggers

-- +Comments
COMMENT ON TABLE companies IS 'Bulk configuration provisioning jobs for device fleets';
COMMENT ON COLUMN companies.id IS 'Primary unique identifier';
COMMENT ON COLUMN companies.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN companies.updated_at IS 'Record last update timestamp';
COMMENT ON COLUMN companies.user_uuid IS 'Uuid of the user who created the provisioning job';
COMMENT ON COLUMN companies.name IS 'Display name of the provisioning job';
COMMENT ON COLUMN companies.status IS 'Job status: pending, running, completed, failed, cancelled';
COMMENT ON COLUMN companies.ttl IS 'Time-to-live for the job in days';
COMMENT ON COLUMN companies.existing_task_action IS 'Action when a device already has a task: skip or overwrite';
COMMENT ON COLUMN companies.launch_mode IS 'Device selection mode: all or selected';
COMMENT ON COLUMN companies.incompatible_action IS 'Action for incompatible devices: exclude or fail';
COMMENT ON COLUMN companies.configuration_source IS 'Configuration source: device or template';
COMMENT ON COLUMN companies.configuration_source_data IS 'IMEI of the device used as configuration source when configuration_source is device';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS set_updated_at_companies_trigger ON companies;
DROP FUNCTION IF EXISTS set_updated_at_companies();

DROP TABLE IF EXISTS companies;
-- +goose StatementEnd
