-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS analytics_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT (timezone('UTC', now())),
    user_uuid VARCHAR(255) NOT NULL,

    is_online BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT fk_analytics_users_user FOREIGN KEY (user_uuid) REFERENCES user_cores(user_uuid) ON DELETE CASCADE
);

-- +Indexes
CREATE INDEX IF NOT EXISTS idx_analytics_users_created_at ON analytics_users(created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_users_user_uuid ON analytics_users(user_uuid);
CREATE INDEX IF NOT EXISTS idx_analytics_users_is_online ON analytics_users(is_online);
-- +Indexes

-- +Comments
COMMENT ON TABLE analytics_users IS 'User online status snapshots for analytics';
COMMENT ON COLUMN analytics_users.id IS 'Primary unique identifier';
COMMENT ON COLUMN analytics_users.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN analytics_users.user_uuid IS 'Uuid of the user';
COMMENT ON COLUMN analytics_users.is_online IS 'Whether the user was online at snapshot time';
-- +Comments
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS analytics_users;
-- +goose StatementEnd
