package constants

import "time"

const (
	ADM_RC_KEEP_ALIVE_VALUE   = 0xaa
	NRC_V2_PACKET_HEADER_SIZE = 0x03

	ADM_RC_TYPE_STRING   = 0x01
	ADM_RC_TYPE_GET_SYNC = 0x02
	ADM_RC_TYPE_GET_CFG  = 0x03
	ADM_RC_TYPE_SET_CFG  = 0x04

	ADM_RC_MAX_PACKET_SIZE                    = 4096
	ADM_RC_PACK_TYPE_HELLO_V2                 = 0x01
	ADM_RC_PACK_TYPE_COMMAND_V2               = 0x02
	ADM_RC_PACK_TYPE_STRING_COMMAND_ANSWER_V2 = 0x03
	ADM_RC_PACK_TYPE_SYNC_V2                  = 0x04
	ADM_RC_PACK_TYPE_CFG_V2                   = 0x05

	ADM_RC_HELLO_PACK_SIZE_V2            = 32
	ADM_RC_COMMAND_GET_SYNC_PACK_SIZE_V2 = 4
	ADM_RC_COMMAND_GET_CFG_PACK_SIZE_V2  = 4
	ADM_RC_SYNC_PACK_SIZE_V2             = 13
	IMEI_MAX_SIZE                        = 8
	PASSWORD_MAX_SIZE                    = 8

	ADM_RC_HELLO_PACK_SIZE_V1     = 25
	IDENTIFICATION_PACKET_TYPE_V1 = 0x03
	ADM_RC_PROTOCOL_VERSION_V1    = 0x01
	ADM_ORDINARY_HEADER_SIZE_V1   = 5

	ADM_RC_TYPE_OFFSET               = 0x03
	ADM_RC_CFG_TYPE_CFG_BLOCK_OFFSET = 0x03
	ADM_TIMER_CONNECTED_MS           = 4 * time.Minute /* 11 минут */
)
