export const RESET_COMMAND = 'RESET';
export const PROTOCOL_COMMAND = 'PROTOCOL';
export const BLEAUTOCATCH_FIND_NEARBY_COMMAND = 'BLEAUTOCATCH 65535,-60';
export const BLEAUTOCATCH_FIND_ALL_COMMAND = 'BLEAUTOCATCH 65535,0';
export const BLEAUTOCATCH_STOP_FIND_COMMAND = 'BLEAUTOCATCH 0';
export const BLESENSORINFO_COMMAND = 'BLESENSORINFO';
export const FUELINFO_COMMAND = 'FUELINFO';
export const BLESENSOR_COMMAND = 'BLESENSOR';
export const FUEL_COMMAND = 'FUEL';
export const COM0_COMMAND = 'COM0';
export const ADM20INFO_COMMAND = 'ADM20INFO';
export const ERASE_EEPROM_COMMAND = 'ERASE EEPROM'; // reset terminal and reboot
export const ERASE_FLASH_COMMAND = 'ERASE FLASH'; // reset memory terminal

export const CONFIGURATION_COMMANDS = [ADM20INFO_COMMAND, BLESENSOR_COMMAND, BLESENSORINFO_COMMAND, FUEL_COMMAND, FUELINFO_COMMAND, COM0_COMMAND]; // sse
