export const DYNAMIC_BLACK_BOX = [
	{ title: 'message.navigation-data', state: 'NAVIGATION_CHUNK' },
	{ title: 'label.lbs', state: 'LBS_CHUNK' },
	{ title: 'message.fuel-level-sensors', state: 'FUEL_CHUNK' },
	{ title: 'label.odometer', state: 'ODOMETER_CHUNK' },
	{ title: 'message.analog-inputs', state: 'ANALOG_CHUNK' },
	{ title: 'message.pulse-inputs', state: 'IMPULSE_CHUNK' },
	{ title: 'label.output-discrete', state: 'OUTPUT_CHUNK' },
	{ title: 'label.one-wire', state: 'OW_CHUNK' },
	{ title: 'label.can-log', state: 'CANLOG_CHUNK' },
	{ title: 'label.modbus', state: 'MODBUS_CHUNK' },
	{ title: 'label.adm20-adm21', state: 'ADM20_CHUNK' },
	{ title: 'label.ble-sensors', state: 'ADM3X_CHUNK' },
	{ title: 'label.ble-tags', state: 'BEACON_CHUNK' },
];

export const DBB_CHUNKS = {
	ADM007: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		ODOMETER_CHUNK: 7,
	},
	ADM007BLE: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
	ADM333: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		OW_CHUNK: 8,
		CANLOG_CHUNK: 9,
		MODBUS_CHUNK: 10,
		ADM20_CHUNK: 11,
	},
	ADM333BLE: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
	ADM333V2: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		OW_CHUNK: 8,
		CANLOG_CHUNK: 9,
		MODBUS_CHUNK: 10,
		ADM20_CHUNK: 11,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
	ADM500: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		IMPULSE_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		OW_CHUNK: 8,
		CANLOG_CHUNK: 9,
		MODBUS_CHUNK: 10,
		ADM20_CHUNK: 11,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
		LBS_CHUNK: 14,
	},
	ADMP50: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
	ADMP50LTE: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		LBS_CHUNK: 4,
		FUEL_CHUNK: 5,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
	BASE: {
		NAVIGATION_CHUNK: 0,
		OUTPUT_CHUNK: 2,
		ANALOG_CHUNK: 3,
		LBS_CHUNK: 4,
		IMPULSE_CHUNK: 4,
		FUEL_CHUNK: 5,
		ODOMETER_CHUNK: 7,
		OW_CHUNK: 8,
		CANLOG_CHUNK: 9,
		MODBUS_CHUNK: 10,
		ADM20_CHUNK: 11,
		ADM3X_CHUNK: 12,
		BEACON_CHUNK: 13,
	},
};

export const getDbbChunks = (model?: string, isTemplate?: boolean) => {
	if (isTemplate) return DBB_CHUNKS.ADM500;
	return DBB_CHUNKS[model as keyof typeof DBB_CHUNKS] || DBB_CHUNKS.BASE;
};
